services:
  db:
    image: postgres:16
    container_name: oddgrid-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: oddgrid
      POSTGRES_PASSWORD: oddgrid
      POSTGRES_DB: oddgrid
    ports:
      - "5432:5432"
    volumes:
      - ./docker-data/postgres:/var/lib/postgresql/data

volumes:
  postgres-data:
